# Kubernetes Resources Contract for Todo Chatbot
# This defines the expected Kubernetes resources when deployed

---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: todo-chatbot
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: todo-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: API_URL
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi

---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: todo-chatbot
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: frontend

---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: todo-chatbot
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: todo-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: DATABASE_URL
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: OPENAI_API_KEY
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: JWT_SECRET
            - name: BETTER_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: BETTER_AUTH_SECRET
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: FRONTEND_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi

---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: todo-chatbot
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: backend

---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: todo-chatbot
data:
  FRONTEND_URL: "http://frontend-svc:3000"
  API_URL: "http://backend-svc:8000"

---
# Secret (template - actual values must be base64 encoded)
apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: todo-chatbot
type: Opaque
data:
  DATABASE_URL: ""      # base64 encoded
  OPENAI_API_KEY: ""    # base64 encoded
  JWT_SECRET: ""        # base64 encoded
  BETTER_AUTH_SECRET: "" # base64 encoded
